/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/callback': RouteRecordInfo<
      '/auth/callback',
      '/auth/callback',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ecosystem': RouteRecordInfo<
      '/ecosystem',
      '/ecosystem',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/internal-tools/': RouteRecordInfo<
      '/internal-tools/',
      '/internal-tools',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/internal-tools/calendar-soubiran-dev': RouteRecordInfo<
      '/internal-tools/calendar-soubiran-dev',
      '/internal-tools/calendar-soubiran-dev',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/services/': RouteRecordInfo<
      '/services/',
      '/services',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/services/api-soubiran-dev': RouteRecordInfo<
      '/services/api-soubiran-dev',
      '/services/api-soubiran-dev',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/services/automation-soubiran-dev': RouteRecordInfo<
      '/services/automation-soubiran-dev',
      '/services/automation-soubiran-dev',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/services/mcp-soubiran-dev': RouteRecordInfo<
      '/services/mcp-soubiran-dev',
      '/services/mcp-soubiran-dev',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/services/redeploy-soubiran-dev': RouteRecordInfo<
      '/services/redeploy-soubiran-dev',
      '/services/redeploy-soubiran-dev',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/websites/': RouteRecordInfo<
      '/websites/',
      '/websites',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/websites/code-soubiran-dev': RouteRecordInfo<
      '/websites/code-soubiran-dev',
      '/websites/code-soubiran-dev',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/websites/infra-soubiran-dev': RouteRecordInfo<
      '/websites/infra-soubiran-dev',
      '/websites/infra-soubiran-dev',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/websites/soubiran-dev': RouteRecordInfo<
      '/websites/soubiran-dev',
      '/websites/soubiran-dev',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/websites/talks-soubiran-dev': RouteRecordInfo<
      '/websites/talks-soubiran-dev',
      '/websites/talks-soubiran-dev',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/app/pages/index.md': {
      routes:
        | '/'
      views:
        | never
    }
    'src/app/pages/auth/callback.vue': {
      routes:
        | '/auth/callback'
      views:
        | never
    }
    'src/app/pages/ecosystem.vue': {
      routes:
        | '/ecosystem'
      views:
        | never
    }
    'src/app/pages/internal-tools/index.md': {
      routes:
        | '/internal-tools/'
      views:
        | never
    }
    'src/app/pages/internal-tools/calendar-soubiran-dev.md': {
      routes:
        | '/internal-tools/calendar-soubiran-dev'
      views:
        | never
    }
    'src/app/pages/services/index.md': {
      routes:
        | '/services/'
      views:
        | never
    }
    'src/app/pages/services/api-soubiran-dev.md': {
      routes:
        | '/services/api-soubiran-dev'
      views:
        | never
    }
    'src/app/pages/services/automation-soubiran-dev.md': {
      routes:
        | '/services/automation-soubiran-dev'
      views:
        | never
    }
    'src/app/pages/services/mcp-soubiran-dev.md': {
      routes:
        | '/services/mcp-soubiran-dev'
      views:
        | never
    }
    'src/app/pages/services/redeploy-soubiran-dev.md': {
      routes:
        | '/services/redeploy-soubiran-dev'
      views:
        | never
    }
    'src/app/pages/websites/index.md': {
      routes:
        | '/websites/'
      views:
        | never
    }
    'src/app/pages/websites/code-soubiran-dev.md': {
      routes:
        | '/websites/code-soubiran-dev'
      views:
        | never
    }
    'src/app/pages/websites/infra-soubiran-dev.md': {
      routes:
        | '/websites/infra-soubiran-dev'
      views:
        | never
    }
    'src/app/pages/websites/soubiran-dev.md': {
      routes:
        | '/websites/soubiran-dev'
      views:
        | never
    }
    'src/app/pages/websites/talks-soubiran-dev.md': {
      routes:
        | '/websites/talks-soubiran-dev'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
