/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ecosystem': RouteRecordInfo<
      '/ecosystem',
      '/ecosystem',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/platforms/': RouteRecordInfo<
      '/platforms/',
      '/platforms',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/platforms/automation-soubiran-dev': RouteRecordInfo<
      '/platforms/automation-soubiran-dev',
      '/platforms/automation-soubiran-dev',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/platforms/chat-soubiran-dev': RouteRecordInfo<
      '/platforms/chat-soubiran-dev',
      '/platforms/chat-soubiran-dev',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/platforms/eats-soubiran-dev': RouteRecordInfo<
      '/platforms/eats-soubiran-dev',
      '/platforms/eats-soubiran-dev',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/platforms/quick-news-soubiran-dev': RouteRecordInfo<
      '/platforms/quick-news-soubiran-dev',
      '/platforms/quick-news-soubiran-dev',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/websites/': RouteRecordInfo<
      '/websites/',
      '/websites',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/websites/infra-soubiran-dev': RouteRecordInfo<
      '/websites/infra-soubiran-dev',
      '/websites/infra-soubiran-dev',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/websites/news-soubiran-dev': RouteRecordInfo<
      '/websites/news-soubiran-dev',
      '/websites/news-soubiran-dev',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/websites/preview-soubiran-dev': RouteRecordInfo<
      '/websites/preview-soubiran-dev',
      '/websites/preview-soubiran-dev',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/websites/soubiran-dev': RouteRecordInfo<
      '/websites/soubiran-dev',
      '/websites/soubiran-dev',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/websites/talks-soubiran-dev': RouteRecordInfo<
      '/websites/talks-soubiran-dev',
      '/websites/talks-soubiran-dev',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'pages/index.md': {
      routes:
        | '/'
      views:
        | never
    }
    'pages/ecosystem.vue': {
      routes:
        | '/ecosystem'
      views:
        | never
    }
    'pages/platforms/index.md': {
      routes:
        | '/platforms/'
      views:
        | never
    }
    'pages/platforms/automation-soubiran-dev.md': {
      routes:
        | '/platforms/automation-soubiran-dev'
      views:
        | never
    }
    'pages/platforms/chat-soubiran-dev.md': {
      routes:
        | '/platforms/chat-soubiran-dev'
      views:
        | never
    }
    'pages/platforms/eats-soubiran-dev.md': {
      routes:
        | '/platforms/eats-soubiran-dev'
      views:
        | never
    }
    'pages/platforms/quick-news-soubiran-dev.md': {
      routes:
        | '/platforms/quick-news-soubiran-dev'
      views:
        | never
    }
    'pages/websites/index.md': {
      routes:
        | '/websites/'
      views:
        | never
    }
    'pages/websites/infra-soubiran-dev.md': {
      routes:
        | '/websites/infra-soubiran-dev'
      views:
        | never
    }
    'pages/websites/news-soubiran-dev.md': {
      routes:
        | '/websites/news-soubiran-dev'
      views:
        | never
    }
    'pages/websites/preview-soubiran-dev.md': {
      routes:
        | '/websites/preview-soubiran-dev'
      views:
        | never
    }
    'pages/websites/soubiran-dev.md': {
      routes:
        | '/websites/soubiran-dev'
      views:
        | never
    }
    'pages/websites/talks-soubiran-dev.md': {
      routes:
        | '/websites/talks-soubiran-dev'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
